version: '2.0'
services:
    app:
        image: j4velin/wg_app
        ports:
            - "8080:80"
        links:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: wg
            MYSQL_USER: wg
            MYSQL_PASSWORD: test
    db:
        image: j4velin/wg_db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: wg
            MYSQL_USER: wg
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
